# Language translations for the Global Disease Diagnosis System
# No emojis are used in any of these texts.

LANGUAGES = {
    "English": {
        "home_title": "Global Multimodal Disease Diagnostic System",
        "home_subtitle": "Advanced multi-disease prediction dashboard for Diabetes, Heart Disease, and Obesity using global machine learning models.",
        "get_started": "Get Started",
        "return_home": "Back to Home Page",
        "lang_select": "Select Language",
        "patient_info": "Patient Information",
        "patient_name": "Patient Name",
        "patient_id": "Patient ID",
        "demographics_vitals": "Demographics and Vitals",
        "lifestyle_habits": "Daily Habits",
        "diet_history": "Diet and Medical History",
        "age": "Age (years)",
        "gender": "Gender",
        "male": "Male",
        "female": "Female",
        "height": "Height (meters)",
        "weight": "Weight (kg)",
        "blood_pressure": "Systolic Blood Pressure (mmHg)",
        "cholesterol": "Cholesterol Level (mg/dL)",
        "smoking": "Do you smoke regularly?",
        "exercise": "Physical Exercise Habits",
        "alcohol": "Alcohol Consumption Level",
        "stress": "Daily Stress Level",
        "sleep": "Daily Sleep (hours)",
        "water": "Daily Water Intake (liters)",
        "screentime": "Daily Screen Time (hours)",
        "gen_health": "How do you rate your general health?",
        "family_heart": "Family History of Heart Disease?",
        "family_weight": "Family History of Overweight/Obesity?",
        "veg_freq": "Vegetable Consumption Frequency (1-3)",
        "meals_count": "Number of Main Meals Daily (1-4)",
        "snack_freq": "Snack Consumption Between Meals",
        "yes": "Yes",
        "no_val": "No",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "none": "None",
        "sometimes": "Sometimes",
        "frequently": "Frequently",
        "always": "Always",
        "exc": "Excellent",
        "vgood": "Very Good",
        "good": "Good",
        "fair": "Fair",
        "poor": "Poor",
        "generate_report": "Generate Diagnostic Report",
        "generating": "Processing models and clinical heuristics...",
        "reset": "Start New Diagnosis",
        "results_header": "Diagnostic Results and Risk Assessment",
        "health_status": "Overall Health Status",
        "obesity_status": "Obesity Stage Classification",
        "diab_status": "Diabetes Stage Classification",
        "heart_status": "Cardiovascular Disease Risk",
        "probabilities": "Disease Risk Probabilities",
        "prediab_prob": "Prediabetes Risk Probability",
        "diab_prob": "Diabetes Risk Probability",
        "heart_prob": "Heart Disease Risk Probability",
        "precautions": "Personalized Precautionary Measures",
        "healthy_status": "Healthy",
        "mild_status": "Mild Risk",
        "high_status": "High Risk",
        "critical_status": "Critical",
        "next_btn": "Next",
        "error_name": "Please enter a valid patient name before generating the report."
    },
    "Español": {
        "home_title": "Sistema Global de Diagnostico de Enfermedades",
        "home_subtitle": "Tablero avanzado de prediccion de multiples enfermedades para Diabetes, Enfermedades Cardiacas y Obesidad mediante modelos de aprendizaje automatico.",
        "get_started": "Comenzar",
        "return_home": "Volver a la Pagina de Inicio",
        "lang_select": "Seleccionar Idioma",
        "patient_info": "Informacion del Paciente",
        "patient_name": "Nombre del Paciente",
        "patient_id": "ID del Paciente",
        "demographics_vitals": "Demografia y Signos Vitales",
        "lifestyle_habits": "Habitos Diarios",
        "diet_history": "Dieta e Historial Medico",
        "age": "Edad (anos)",
        "gender": "Genero",
        "male": "Masculino",
        "female": "Femenino",
        "height": "Altura (metros)",
        "weight": "Peso (kg)",
        "blood_pressure": "Presion Arterial Sistolica (mmHg)",
        "cholesterol": "Nivel de Colesterol (mg/dL)",
        "smoking": "Suele fumar regularmente?",
        "exercise": "Habitos de Ejercicio Fisico",
        "alcohol": "Nivel de Consumo de Alcohol",
        "stress": "Nivel de Estres Diario",
        "sleep": "Horas de Sueno Diarias",
        "water": "Consumo Diario de Agua (litros)",
        "screentime": "Tiempo Diario de Pantalla (horas)",
        "gen_health": "Como califica su salud general?",
        "family_heart": "Historial Familiar de Enfermedades Cardiacas?",
        "family_weight": "Historial Familiar de Sobrepeso/Obesidad?",
        "veg_freq": "Frecuencia de Consumo de Verduras (1-3)",
        "meals_count": "Numero de Comidas Principales al Dia (1-4)",
        "snack_freq": "Consumo de Alimentos Entre Comidas",
        "yes": "Si",
        "no_val": "No",
        "high": "Alto",
        "medium": "Medio",
        "low": "Bajo",
        "none": "Ninguno",
        "sometimes": "A veces",
        "frequently": "Frecuentemente",
        "always": "Siempre",
        "exc": "Excelente",
        "vgood": "Muy Bueno",
        "good": "Bueno",
        "fair": "Regular",
        "poor": "Deficiente",
        "generate_report": "Generar Informe de Diagnostico",
        "generating": "Procesando modelos y heuristicas clinicas...",
        "reset": "Iniciar Nuevo Diagnostico",
        "results_header": "Resultados de Diagnostico y Evaluacion de Riesgos",
        "health_status": "Estado de Salud General",
        "obesity_status": "Clasificacion de la Etapa de Obesidad",
        "diab_status": "Clasificacion de la Etapa de Diabetes",
        "heart_status": "Riesgo de Enfermedad Cardiovascular",
        "probabilities": "Probabilidades de Riesgo de Enfermedad",
        "prediab_prob": "Probabilidad de Riesgo de Prediabetes",
        "diab_prob": "Probabilidad de Riesgo de Diabetes",
        "heart_prob": "Probabilidad de Riesgo de Enfermedad Cardiaca",
        "precautions": "Medidas de Precaucion Personalizadas",
        "healthy_status": "Saludable",
        "mild_status": "Riesgo Leve",
        "high_status": "Riesgo Alto",
        "critical_status": "Critico",
        "next_btn": "Siguiente",
        "error_name": "Por favor, ingrese un nombre de paciente valido antes de generar el informe."
    },
    "Français": {
        "home_title": "Systeme Global de Diagnostic de Maladies",
        "home_subtitle": "Tableau de bord de prediction multi-maladies pour le diabete, les maladies cardiaques et l'obesite utilisant des modeles d'apprentissage automatique.",
        "get_started": "Commencer",
        "return_home": "Retour a la Page d'Accueil",
        "lang_select": "Choisir la Langue",
        "patient_info": "Informations du Patient",
        "patient_name": "Nom du Patient",
        "patient_id": "ID du Patient",
        "demographics_vitals": "Demographie et Signes Vitaux",
        "lifestyle_habits": "Habitudes Quotidiennes",
        "diet_history": "Alimentation et Historique Medical",
        "age": "Age (ans)",
        "gender": "Genre",
        "male": "Homme",
        "female": "Femme",
        "height": "Taille (metres)",
        "weight": "Poids (kg)",
        "blood_pressure": "Pression Arterielle Systolique (mmHg)",
        "cholesterol": "Taux de Cholesterol (mg/dL)",
        "smoking": "Fumez-vous regulierement?",
        "exercise": "Habitudes d'Exercice Physique",
        "alcohol": "Niveau de Consommation d'Alcool",
        "stress": "Niveau de Stress Quotidien",
        "sleep": "Sommeil Quotidien (heures)",
        "water": "Consommation d'Eau Quotidienne (litres)",
        "screentime": "Temps d'Ecran Quotidien (heures)",
        "gen_health": "Comment evaluez-vous votre sante generale?",
        "family_heart": "Antecedents Familiaux de Maladie Cardiaque?",
        "family_weight": "Antecedents Familiaux de Surpoids/Obesite?",
        "veg_freq": "Frequence de Consommation de Legumes (1-3)",
        "meals_count": "Nombre de Repas Principaux par Jour (1-4)",
        "snack_freq": "Grignotage Entre les Repas",
        "yes": "Oui",
        "no_val": "Non",
        "high": "Eleve",
        "medium": "Moyen",
        "low": "Faible",
        "none": "Aucun",
        "sometimes": "Parfois",
        "frequently": "Frequemment",
        "always": "Toujours",
        "exc": "Excellent",
        "vgood": "Tres Bon",
        "good": "Bon",
        "fair": "Moyen",
        "poor": "Mauvais",
        "generate_report": "Generer le Rapport de Diagnostic",
        "generating": "Traitement des modeles et des heuristiques cliniques...",
        "reset": "Commencer un Nouveau Diagnostic",
        "results_header": "Resultats du Diagnostic et Evaluation des Risques",
        "health_status": "Etat de Sante General",
        "obesity_status": "Classification du Stade d'Obesite",
        "diab_status": "Classification du Stade de Diabete",
        "heart_status": "Risque de Maladie Cardiovasculaire",
        "probabilities": "Probabilites de Risque de Maladie",
        "prediab_prob": "Risque de Prediabete",
        "diab_prob": "Risque de Diabete",
        "heart_prob": "Risque de Maladie Cardiaque",
        "precautions": "Mesures de Precaution Personnalisees",
        "healthy_status": "Sain",
        "mild_status": "Risque Modere",
        "high_status": "Risque Eleve",
        "critical_status": "Critique",
        "next_btn": "Suivant",
        "error_name": "Veuillez entrer un nom de patient valide avant de generer le rapport."
    },
    "Chinese": {
        "home_title": "全球多模态疾病诊断系统",
        "home_subtitle": "基于全球机器学习模型的糖尿病、心脏病与肥胖症多疾病预测系统。",
        "get_started": "开始诊断",
        "return_home": "返回主页",
        "lang_select": "选择语言",
        "patient_info": "患者信息",
        "patient_name": "患者姓名",
        "patient_id": "患者ID",
        "demographics_vitals": "人口学及生命体征",
        "lifestyle_habits": "日常习惯",
        "diet_history": "饮食与医疗史",
        "age": "年龄 (岁)",
        "gender": "性别",
        "male": "男",
        "female": "女",
        "height": "身高 (米)",
        "weight": "体重 (公斤)",
        "blood_pressure": "收缩压 (mmHg)",
        "cholesterol": "胆固醇水平 (mg/dL)",
        "smoking": "您定期吸烟吗？",
        "exercise": "体育运动习惯",
        "alcohol": "饮酒频率/程度",
        "stress": "每日压力水平",
        "sleep": "每日睡眠时间 (小时)",
        "water": "每日饮水量 (升)",
        "screentime": "每日屏幕时间 (小时)",
        "gen_health": "您如何评估自身的总体健康状况？",
        "family_heart": "是否有心脏病家族史？",
        "family_weight": "是否有超重/肥胖家族史？",
        "veg_freq": "蔬菜摄入频率 (1-3)",
        "meals_count": "每日正餐次数 (1-4)",
        "snack_freq": "两餐之间吃零食的习惯",
        "yes": "是",
        "no_val": "否",
        "high": "高",
        "medium": "中",
        "low": "低",
        "none": "无",
        "sometimes": "有时",
        "frequently": "经常",
        "always": "总是",
        "exc": "极好",
        "vgood": "很好",
        "good": "一般",
        "fair": "较差",
        "poor": "极差",
        "generate_report": "生成诊断报告",
        "generating": "模型与临床启发式计算中...",
        "reset": "开始新诊断",
        "results_header": "诊断结果与风险评估",
        "health_status": "总体健康状态",
        "obesity_status": "肥胖阶段分类",
        "diab_status": "糖尿病阶段分类",
        "heart_status": "心血管疾病风险",
        "probabilities": "疾病风险概率",
        "prediab_prob": "糖尿病前期风险概率",
        "diab_prob": "糖尿病风险概率",
        "heart_prob": "心脏病风险概率",
        "precautions": "个性化预防性健康建议",
        "healthy_status": "健康",
        "mild_status": "轻度风险",
        "high_status": "高风险",
        "critical_status": "危急",
        "next_btn": "下一步",
        "error_name": "生成报告前请输入有效的患者姓名。"
    },
    "Arabic": {
        "home_title": "النظام العالمي لتشخيص الأمراض متعدد النماذج",
        "home_subtitle": "لوحة متقدمة للتنبؤ بأمراض السكري والقلب والسمنة باستخدام نماذج التعلم الآلي العالمية.",
        "get_started": "ابدأ الآن",
        "return_home": "العودة إلى الصفحة الرئيسية",
        "lang_select": "اختر اللغة",
        "patient_info": "بيانات المريض",
        "patient_name": "اسم المريض",
        "patient_id": "معرف المريض",
        "demographics_vitals": "البيانات الديموغرافية والعلامات الحيوية",
        "lifestyle_habits": "العادات اليومية",
        "diet_history": "النظام الغذائي والتاريخ الطبي",
        "age": "العمر (بالسنوات)",
        "gender": "الجنس",
        "male": "ذكر",
        "female": "أنثى",
        "height": "الطول (بالمتر)",
        "weight": "الوزن (بالكيلوجرام)",
        "blood_pressure": "ضغط الدم الانقباضي (ملم زئبق)",
        "cholesterol": "مستوى الكوليسترول (ملجم/ديسيبل)",
        "smoking": "هل تدخن بانتظام؟",
        "exercise": "عادات ممارسة الرياضة البدنية",
        "alcohol": "مستوى استهلاك الكحول",
        "stress": "مستوى التوتر اليومي",
        "sleep": "ساعات النوم اليومية",
        "water": "معدل شرب الماء اليومي (لتر)",
        "screentime": "ساعات استخدام الشاشات يوميا",
        "gen_health": "كيف تقيم حالتك الصحية العامة؟",
        "family_heart": "هل يوجد تاريخ عائلي لأمراض القلب؟",
        "family_weight": "هل يوجد تاريخ عائلي للسمنة أو زيادة الوزن؟",
        "veg_freq": "معدل تناول الخضروات (1-3)",
        "meals_count": "عدد الوجبات الرئيسية يوميا (1-4)",
        "snack_freq": "تناول وجبات خفيفة بين الوجبات الرئيسية",
        "yes": "نعم",
        "no_val": "لا",
        "high": "مرتفع",
        "medium": "متوسط",
        "low": "منخفض",
        "none": "لا يوجد",
        "sometimes": "أحيانا",
        "frequently": "غالبا",
        "always": "دائما",
        "exc": "ممتاز",
        "vgood": "جيد جدا",
        "good": "جيد",
        "fair": "مقبول",
        "poor": "ضعيف",
        "generate_report": "إنشاء تقرير التشخيص",
        "generating": "جاري معالجة النماذج والمعايير السريرية...",
        "reset": "بدء تشخيص جديد",
        "results_header": "نتائج التشخيص وتقييم المخاطر",
        "health_status": "الحالة الصحية العامة",
        "obesity_status": "تصنيف مرحلة السمنة",
        "diab_status": "تصنيف مرحلة مرض السكري",
        "heart_status": "مخاطر أمراض القلب والأوعية الدموية",
        "probabilities": "احتمالات خطر الإصابة بالأمراض",
        "prediab_prob": "احتمال خطر مرحلة ما قبل السكري",
        "diab_prob": "احتمال خطر السكري",
        "heart_prob": "احتمال خطر أمراض القلب",
        "precautions": "التدابير الوقائية المخصصة",
        "healthy_status": "سليم صحيا",
        "mild_status": "خطر طفيف",
        "high_status": "خطر مرتفع",
        "critical_status": "حرج جدا",
        "next_btn": "التالي",
        "error_name": "يرجى إدخال اسم مريض صحيح قبل إنشاء التقرير."
    },
    "Hindi": {
        "home_title": "वैश्विक बहु-विषयक रोग निदान प्रणाली",
        "home_subtitle": "मशीन लर्निंग मॉडल का उपयोग करके मधुमेह, हृदय रोग और मोटापे के लिए उन्नत पूर्वानुमान प्रणाली।",
        "get_started": "शुरू करें",
        "return_home": "मुख्य पृष्ठ पर जाएं",
        "lang_select": "भाषा चुनें",
        "patient_info": "मरीज की जानकारी",
        "patient_name": "मरीज का नाम",
        "patient_id": "मरीज आईडी",
        "demographics_vitals": "जनसांख्यिकी और महत्वपूर्ण आंकड़े",
        "lifestyle_habits": "दैनिक आदतें",
        "diet_history": "आहार और चिकित्सा इतिहास",
        "age": "उम्र (वर्ष)",
        "gender": "लिंग",
        "male": "पुरुष",
        "female": "महिला",
        "height": "लंबाई (मीटर)",
        "weight": "वजन (किग्रा)",
        "blood_pressure": "सिस्टोलिक रक्तचाप (mmHg)",
        "cholesterol": "कोलेस्ट्रॉल का स्तर (mg/dL)",
        "smoking": "क्या आप नियमित रूप से धूम्रपान करते हैं?",
        "exercise": "शारीरिक व्यायाम की आदतें",
        "alcohol": "शराब का सेवन स्तर",
        "stress": "दैनिक तनाव का स्तर",
        "sleep": "दैनिक नींद (घंटे)",
        "water": "दैनिक पानी का सेवन (लीटर)",
        "screentime": "दैनिक स्क्रीन समय (घंटे)",
        "gen_health": "आप अपने सामान्य स्वास्थ्य को कैसा आंकते हैं?",
        "family_heart": "क्या परिवार में हृदय रोग का इतिहास है?",
        "family_weight": "क्या परिवार में मोटापे का इतिहास है?",
        "veg_freq": "सब्जी खाने की आवृत्ति (1-3)",
        "meals_count": "दैनिक मुख्य भोजन की संख्या (1-4)",
        "snack_freq": "भोजन के बीच स्नैक्स खाने की आदत",
        "yes": "हाँ",
        "no_val": "नहीं",
        "high": "उच्च",
        "medium": "मध्यम",
        "low": "कम",
        "none": "कोई नहीं",
        "sometimes": "कभी-कभी",
        "frequently": "अक्सर",
        "always": "हमेशा",
        "exc": "बहुत बढ़िया",
        "vgood": "बहुत अच्छा",
        "good": "अच्छा",
        "fair": "ठीक-ठाक",
        "poor": "खराब",
        "generate_report": "निदान रिपोर्ट तैयार करें",
        "generating": "मॉडल और नैदानिक गणना की जा रही है...",
        "reset": "नया निदान शुरू करें",
        "results_header": "निदान परिणाम और जोखिम मूल्यांकन",
        "health_status": "कुल मिलाकर स्वास्थ्य स्थिति",
        "obesity_status": "मोटापा चरण वर्गीकरण",
        "diab_status": "मधुमेह चरण वर्गीकरण",
        "heart_status": "हृदय रोग का जोखिम",
        "probabilities": "रोग जोखिम की संभावनाएं",
        "prediab_prob": "प्री-डायबिटीज जोखिम संभावना",
        "diab_prob": "मधुमेह जोखिम संभावना",
        "heart_prob": "हृदय रोग जोखिम संभावना",
        "precautions": "व्यक्तिगत निवारक उपाय",
        "healthy_status": "स्वस्थ",
        "mild_status": "हल्का जोखिम",
        "high_status": "उच्च जोखिम",
        "critical_status": "गंभीर",
        "next_btn": "आगे",
        "error_name": "कृपया रिपोर्ट तैयार करने से पहले मरीज का नाम दर्ज करें।"
    },
    "Urdu": {
        "home_title": "عالمی کثیر الجہتی تشخیصی نظامِ امراض",
        "home_subtitle": "عالمی مشین لرننگ ماڈلز کے ذریعے شوگر، دل کے امراض، اور موٹاپے کی پیش گوئی کے لیے جدید ترین ڈیش بورڈ۔",
        "get_started": "شروع کریں",
        "return_home": "مرکزی صفحہ پر جائیں",
        "lang_select": "زبان منتخب کریں",
        "patient_info": "مریض کی معلومات",
        "patient_name": "مریض کا نام",
        "patient_id": "مریض کی شناختی نمبر",
        "demographics_vitals": "آبادیاتی اور اہم علامات",
        "lifestyle_habits": "روزمرہ کی عادات",
        "diet_history": "غذا اور طبی تاریخ",
        "age": "عمر (سال)",
        "gender": "جنس",
        "male": "مرد",
        "female": "عورت",
        "height": "قد (میٹر)",
        "weight": "وزن (کلوگرام)",
        "blood_pressure": "سسٹولک بلڈ پریشر (mmHg)",
        "cholesterol": "کولیسٹرول کی سطح (mg/dL)",
        "smoking": "کیا آپ باقاعدگی سے سگریٹ نوشی کرتے ہیں؟",
        "exercise": "ورزش کی عادات",
        "alcohol": "شراب نوشی کی سطح",
        "stress": "روزمرہ ذہنی تناؤ کی سطح",
        "sleep": "روزانہ نیند (گھنٹے)",
        "water": "روزانہ پانی پینے کی مقدار (لیٹر)",
        "screentime": "روزانہ اسکرین ٹائم (گھنٹے)",
        "gen_health": "آپ اپنی عمومی صحت کو کیسا درجہ دیتے ہیں؟",
        "family_heart": "کیا دل کی بیماری کی خاندانی تاریخ ہے؟",
        "family_weight": "کیا موٹاپے کی خاندانی تاریخ ہے؟",
        "veg_freq": "سبزی کھانے کی کثرت (1-3)",
        "meals_count": "روزانہ کھانے کی تعداد (1-4)",
        "snack_freq": "کھانے کے درمیان ہلکی غذا لینے کی عادت",
        "yes": "جی ہاں",
        "no_val": "جی نہیں",
        "high": "زیادہ",
        "medium": "درمیانہ",
        "low": "کم",
        "none": "کوئی نہیں",
        "sometimes": "کبھی کبھی",
        "frequently": "اکثر",
        "always": "ہمیشہ",
        "exc": "بہترین",
        "vgood": "بہت اچھا",
        "good": "اچھا",
        "fair": "مناسب",
        "poor": "کمزور",
        "generate_report": "تشخیصی رپورٹ حاصل کریں",
        "generating": "ماڈلز اور طبی حساب کتاب جاری ہے...",
        "reset": "نیا معائنہ شروع کریں",
        "results_header": "تشخیصی نتائج اور خطرات کا جائزہ",
        "health_status": "مجموعی صحت کی صورتحال",
        "obesity_status": "موٹاپے کے مرحلے کی درجہ بندی",
        "diab_status": "شوگر کے مرحلے کی درجہ بندی",
        "heart_status": "دل کی بیماری کا خطرہ",
        "probabilities": "بیماریوں کے خطرات کا تناسب",
        "prediab_prob": "شوگر سے پہلے کے مرحلے کا خطرہ",
        "diab_prob": "شوگر کا خطرہ",
        "heart_prob": "دل کی بیماری کا خطرہ",
        "precautions": "انفرادی احتیاطی تدابير",
        "healthy_status": "صحت مند",
        "mild_status": "معمولی خطرہ",
        "high_status": "زیادہ خطرہ",
        "critical_status": "انتہائی تشویشناک",
        "next_btn": "اگلا",
        "error_name": "رپورٹ تیار کرنے سے پہلے براہ کرم مریض کا نام درج کریں۔"
    }
}
